/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.cientifica;


import javax.swing.JOptionPane;
import java.awt.Color;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bailarina77
 */
public class Calculadora extends javax.swing.JFrame {
    private boolean igual,inicio=true, operacion1,operacion2;
    private double a,b,c,memoria=0,resultado,valor1,valor2,cos,sin,tan;
    private String cadena,funciones,tipoOperaciones;
    Funciones f= new Funciones();
    
    
    
   
    public Calculadora() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        Button_Porcentaje = new javax.swing.JButton();
        Button_N1 = new javax.swing.JButton();
        Button_N4 = new javax.swing.JButton();
        Button_Sin = new javax.swing.JButton();
        Button_Tan = new javax.swing.JButton();
        Button_N5 = new javax.swing.JButton();
        Button_N3 = new javax.swing.JButton();
        Button_Cos = new javax.swing.JButton();
        Button_RaizCuadrada = new javax.swing.JButton();
        Button_N6 = new javax.swing.JButton();
        Button_C = new javax.swing.JButton();
        Button_Multiplicacion = new javax.swing.JButton();
        Button_CE = new javax.swing.JButton();
        Button_N9 = new javax.swing.JButton();
        Button_Exponente = new javax.swing.JButton();
        Button_Division = new javax.swing.JButton();
        Button_PI = new javax.swing.JButton();
        Button_N2 = new javax.swing.JButton();
        Button_Signo = new javax.swing.JButton();
        Button_N7 = new javax.swing.JButton();
        Button_N8 = new javax.swing.JButton();
        Button_EXP = new javax.swing.JButton();
        Button_10levarX = new javax.swing.JButton();
        Button_Decimal = new javax.swing.JButton();
        Button_N0 = new javax.swing.JButton();
        Button_log = new javax.swing.JButton();
        Button_Factorial = new javax.swing.JButton();
        Button_gual = new javax.swing.JButton();
        Button_Resta = new javax.swing.JButton();
        Button_Suma = new javax.swing.JButton();
        Button_E = new javax.swing.JButton();
        Button_Retroseso = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TextField_Principal = new javax.swing.JTextField();
        TextField_Previo = new javax.swing.JTextField();
        RadioButton_Sexages = new javax.swing.JRadioButton();
        Historial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        holaxd = new javax.swing.JTextArea();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");

        Button_Porcentaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Porcentaje.setText("%");
        Button_Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PorcentajeActionPerformed(evt);
            }
        });

        Button_N1.setBackground(new java.awt.Color(255, 255, 255));
        Button_N1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N1.setText("1");
        Button_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N1ActionPerformed(evt);
            }
        });

        Button_N4.setBackground(new java.awt.Color(255, 255, 255));
        Button_N4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N4.setText("4");
        Button_N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N4ActionPerformed(evt);
            }
        });

        Button_Sin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Sin.setText("sin");
        Button_Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SinActionPerformed(evt);
            }
        });

        Button_Tan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Tan.setText("tan");
        Button_Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TanActionPerformed(evt);
            }
        });

        Button_N5.setBackground(new java.awt.Color(255, 255, 255));
        Button_N5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N5.setText("5");
        Button_N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N5ActionPerformed(evt);
            }
        });

        Button_N3.setBackground(new java.awt.Color(255, 255, 255));
        Button_N3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N3.setText("3");
        Button_N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N3ActionPerformed(evt);
            }
        });

        Button_Cos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Cos.setText("cos");
        Button_Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CosActionPerformed(evt);
            }
        });

        Button_RaizCuadrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_RaizCuadrada.setText("√");
        Button_RaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RaizCuadradaActionPerformed(evt);
            }
        });

        Button_N6.setBackground(new java.awt.Color(255, 255, 255));
        Button_N6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N6.setText("6");
        Button_N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N6ActionPerformed(evt);
            }
        });

        Button_C.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_C.setForeground(new java.awt.Color(251, 54, 1));
        Button_C.setText("C");
        Button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CActionPerformed(evt);
            }
        });

        Button_Multiplicacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Multiplicacion.setText("*");
        Button_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MultiplicacionActionPerformed(evt);
            }
        });

        Button_CE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_CE.setForeground(new java.awt.Color(251, 115, 0));
        Button_CE.setText("CE");
        Button_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CEActionPerformed(evt);
            }
        });

        Button_N9.setBackground(new java.awt.Color(255, 255, 255));
        Button_N9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N9.setText("9");
        Button_N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N9ActionPerformed(evt);
            }
        });

        Button_Exponente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Exponente.setText("x^y");
        Button_Exponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExponenteActionPerformed(evt);
            }
        });

        Button_Division.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Division.setText("/");
        Button_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DivisionActionPerformed(evt);
            }
        });

        Button_PI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_PI.setText("pi(π)");
        Button_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PIActionPerformed(evt);
            }
        });

        Button_N2.setBackground(new java.awt.Color(255, 255, 255));
        Button_N2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N2.setText("2");
        Button_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N2ActionPerformed(evt);
            }
        });

        Button_Signo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Signo.setText("±");
        Button_Signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignoActionPerformed(evt);
            }
        });

        Button_N7.setBackground(new java.awt.Color(255, 255, 255));
        Button_N7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N7.setText("7");
        Button_N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N7ActionPerformed(evt);
            }
        });

        Button_N8.setBackground(new java.awt.Color(255, 255, 255));
        Button_N8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N8.setText("8");
        Button_N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N8ActionPerformed(evt);
            }
        });

        Button_EXP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_EXP.setText("EXP");
        Button_EXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EXPActionPerformed(evt);
            }
        });

        Button_10levarX.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        Button_10levarX.setText("10^x");
        Button_10levarX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_10levarXActionPerformed(evt);
            }
        });

        Button_Decimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Decimal.setText(".");
        Button_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DecimalActionPerformed(evt);
            }
        });

        Button_N0.setBackground(new java.awt.Color(255, 255, 255));
        Button_N0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_N0.setText("0");
        Button_N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N0ActionPerformed(evt);
            }
        });

        Button_log.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_log.setText("log");
        Button_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_logActionPerformed(evt);
            }
        });

        Button_Factorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Factorial.setText("n!");
        Button_Factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FactorialActionPerformed(evt);
            }
        });

        Button_gual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_gual.setText("=");
        Button_gual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_gualActionPerformed(evt);
            }
        });

        Button_Resta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Resta.setText("-");
        Button_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RestaActionPerformed(evt);
            }
        });

        Button_Suma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_Suma.setText("+");
        Button_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SumaActionPerformed(evt);
            }
        });

        Button_E.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button_E.setText("e");
        Button_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EActionPerformed(evt);
            }
        });

        Button_Retroseso.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Button_Retroseso.setText("<--");
        Button_Retroseso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetrosesoActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextField_Principal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TextField_Principal.setForeground(new java.awt.Color(0, 51, 153));
        TextField_Principal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextField_Principal.setText("0 ");
        TextField_Principal.setToolTipText("");
        TextField_Principal.setFocusable(false);
        jPanel1.add(TextField_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 469, 48));

        TextField_Previo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextField_Previo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextField_Previo.setText(" ");
        TextField_Previo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextField_Previo.setFocusable(false);
        jPanel1.add(TextField_Previo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 469, 24));

        buttonGroup1.add(RadioButton_Sexages);
        RadioButton_Sexages.setSelected(true);
        RadioButton_Sexages.setText("Sexages");

        Historial.setText("Historial");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });

        holaxd.setEditable(false);
        holaxd.setColumns(20);
        holaxd.setRows(5);
        jScrollPane1.setViewportView(holaxd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Signo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_gual, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(RadioButton_Sexages))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Retroseso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_RaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_CE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_10levarX, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_EXP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_log, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_PI, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Exponente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_E, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Button_N4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_N7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_N6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_N8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_N9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Button_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_N5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Button_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Button_N0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Button_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_N2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Button_N3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_Multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(Historial))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Button_N7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_N8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_N9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Button_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Button_N4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Button_N6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_N5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Button_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(Button_N1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Button_N2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Button_N3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Button_Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_Cos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Button_PI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_Exponente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_E, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Button_10levarX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_EXP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_log, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Button_Factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_RaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Button_Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_Retroseso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Button_N0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(RadioButton_Sexages)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Signo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_gual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Historial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Botones numericos
    private void Button_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N1ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("1");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"1");
        }
    }//GEN-LAST:event_Button_N1ActionPerformed

    private void Button_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N2ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("2");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"2");
        }
    }//GEN-LAST:event_Button_N2ActionPerformed

    private void Button_N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N3ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("3");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"3");
        }        
    }//GEN-LAST:event_Button_N3ActionPerformed

    private void Button_N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N4ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("4");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"4");
        }       
    }//GEN-LAST:event_Button_N4ActionPerformed

    private void Button_N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N5ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("5");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"5");
        }        
    }//GEN-LAST:event_Button_N5ActionPerformed

    private void Button_N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N6ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("6");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"6");
        }        
    }//GEN-LAST:event_Button_N6ActionPerformed

    private void Button_N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N7ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("7");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"7");
        }        
    }//GEN-LAST:event_Button_N7ActionPerformed

    private void Button_N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N8ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("8");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"8");
        }      
    }//GEN-LAST:event_Button_N8ActionPerformed

    private void Button_N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N9ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("9");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"9");
        }       
    }//GEN-LAST:event_Button_N9ActionPerformed

    private void Button_N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N0ActionPerformed
        if(inicio==true){
            TextField_Principal.setText(" ");
            TextField_Principal.setText("0");
            inicio=false;
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+"0");
        }        
    }//GEN-LAST:event_Button_N0ActionPerformed
    //Botón la función de punto decimal
    private void Button_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DecimalActionPerformed
        if(TextField_Principal.getText().contains(" .")){
            
        }else{
            TextField_Principal.setText(TextField_Principal.getText()+" .");
            inicio=false;
        }
    }//GEN-LAST:event_Button_DecimalActionPerformed
//Botón de la función de suma
    private void Button_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SumaActionPerformed
        igual=true;
        inicio=true;
        if(operacion1 = true){
            valor1= Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText()+ "+");
            operacion1= false;
        }else{
        if(operacion2 = true){
            valor2= Double.parseDouble(TextField_Principal.getText());        
            TextField_Previo.setText(TextField_Principal.getText()+ "+");
            operacion2= false;
        }else{
            TextField_Previo.setText(TextField_Principal.getText()+ "+");
            Operaciones(resultado, valor2);
            }            
        }
        tipoOperaciones="+";
    }//GEN-LAST:event_Button_SumaActionPerformed
//Botón de la función de resta
    private void Button_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RestaActionPerformed
        igual=true;
        inicio=true;
        if(operacion1 = true){
            valor1= Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText()+ "-");
            operacion1= false;
        }else{
        if(operacion2 = true){
            valor2= Double.parseDouble(TextField_Principal.getText());        
            TextField_Previo.setText(TextField_Principal.getText()+ "-");
            operacion2= false;
        }else{
            TextField_Previo.setText(TextField_Principal.getText()+ "-");
            Operaciones(resultado, valor2);
            }            
        }
        tipoOperaciones="-";       
    }//GEN-LAST:event_Button_RestaActionPerformed
//Botón de la función de multiplicar
    private void Button_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MultiplicacionActionPerformed
        igual=true;
        inicio=true;
        if(operacion1 = true){
            valor1= Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText()+ "*");
            operacion1= false;
        }else{
        if(operacion2 = true){
            valor2= Double.parseDouble(TextField_Principal.getText());        
            TextField_Previo.setText(TextField_Principal.getText()+ "*");
            operacion2= false;
        }else{
            TextField_Previo.setText(TextField_Principal.getText()+ "*");
            Operaciones(resultado, valor2);
            }            
        }
        tipoOperaciones="*";       
    }//GEN-LAST:event_Button_MultiplicacionActionPerformed
//Botón de la función de división
    private void Button_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DivisionActionPerformed
        igual=true;
        inicio=true;
        if(operacion1 = true){
            valor1= Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText()+ "/");
            operacion1= false;
        }else{
        if(operacion2 = true){
            valor2= Double.parseDouble(TextField_Principal.getText());        
            TextField_Previo.setText(TextField_Principal.getText()+ "/");
            operacion2= false;
        }else{
            TextField_Previo.setText(TextField_Principal.getText()+ "/");
            Operaciones(resultado, valor2);
            }            
        }
        tipoOperaciones="/";        
    }//GEN-LAST:event_Button_DivisionActionPerformed

//METODOS PARA OPERACIONES
    private void Operaciones(double valor1, double valor2){
        switch(tipoOperaciones){
            //PARA LA SUMA
            case "+":
                resultado=valor1+valor2;
                TextField_Principal.setText(resultado+"");
                valor1= Double.parseDouble(TextField_Principal.getText());
            break;
            //PARA RESTA
            case "-":
                resultado=valor1-valor2;
                TextField_Principal.setText(resultado+"");
                valor1= Double.parseDouble(TextField_Principal.getText());
            break;

            //PARA MULTIPLICACION
            case "*":
                resultado=valor1*valor2;
                TextField_Principal.setText(resultado+"");
                valor1= Double.parseDouble(TextField_Principal.getText());
            break;               
            
            //PARA DIVISION
            case "/":
                if(valor2==0){
                    TextField_Principal.setText("ERROR XD");
                    break;
                }else{
                resultado=valor1/valor2;
                TextField_Principal.setText(resultado+"");
                valor1= Double.parseDouble(TextField_Principal.getText());
                break;           
                }
                
            case "potencia":
                resultado=Math.pow(valor1,valor2);
                TextField_Principal.setText(resultado+"");
                break;
        }       
    }
    
//Botón de la función de igual
    private void Button_gualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_gualActionPerformed
        inicio=true;
        operacion1=true;
        if(igual==true){
            if(tipoOperaciones==null){
                
            }else{
                 valor2= Double.parseDouble(TextField_Principal.getText());
                 TextField_Previo.setText(TextField_Previo.getText()+TextField_Principal.getText());       
                 Operaciones(valor1, valor2);
                 try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
                 }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
                 }
                 igual=false;
            }
        }else{
            TextField_Previo.setText("");
            Operaciones(valor1,valor2);
        }
    }//GEN-LAST:event_Button_gualActionPerformed
//Botón con la función de RAIZ CUADRADA
    private void Button_RaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RaizCuadradaActionPerformed
        valor1=Double.parseDouble(TextField_Principal.getText());
        if(valor1>=0){
            TextField_Previo.setText("sqrt( "+valor1+")");
            TextField_Principal.setText(Math.sqrt(valor1)+" ");
            //SERIALIZAR OPERACION
            try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
            }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
            }
            
        }else{
            TextField_Principal.setText("Error");
        }
    }//GEN-LAST:event_Button_RaizCuadradaActionPerformed
//Botón con la función de PORCENTAJE
    private void Button_PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PorcentajeActionPerformed
        valor2=Double.parseDouble(TextField_Principal.getText());
        TextField_Previo.setText(TextField_Previo.getText()+TextField_Principal.getText());
        TextField_Principal.setText((valor1*valor2)/100+""); 
        igual=true;
        //SERIALIZAR OPERACION
        try{
            f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
        }
        
        
    }//GEN-LAST:event_Button_PorcentajeActionPerformed

//Botón que realiza la operación cambio de signo
    private void Button_SignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignoActionPerformed
      double nu1=0, nu2, nu3;
      nu2=Double.parseDouble(TextField_Principal.getText());
      nu3=nu1-nu2;
      TextField_Principal.setText(nu3+"");
    }//GEN-LAST:event_Button_SignoActionPerformed
 //Botón con la función de C
    private void Button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CActionPerformed
       TextField_Principal.setText("0");
       TextField_Previo.setText("");
       inicio=true;
       funciones="";
       operacion1=true;
       operacion2=true;
       igual=true;
       valor1=0;
       valor2=0;
       resultado=0;
    }//GEN-LAST:event_Button_CActionPerformed
 //Botón con la función de CE
    private void Button_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CEActionPerformed
       TextField_Principal.setText("0");
       TextField_Previo.setText("0");
       inicio=true;
       funciones="";
    }//GEN-LAST:event_Button_CEActionPerformed
//Botón con la función de RETROCEDER
    private void Button_RetrosesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetrosesoActionPerformed
      if(TextField_Principal.getText().length()>1){
          TextField_Principal.setText(TextField_Principal.getText().substring(0,TextField_Principal.getText().length()-1));
      
          if(TextField_Principal.getText().length()==1){
              TextField_Principal.setText("0");
              inicio=true;
          }
      }
    }//GEN-LAST:event_Button_RetrosesoActionPerformed
    
    //METODO PARA FUNCIONES TRIGONOMETRICAS
    public void Trigonometria(){
        if(RadioButton_Sexages.isSelected()){
            switch(funciones){
                case "sin":
                    valor1=Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" sin("+valor1+")");
                    sin=Math.sin(Math.PI*(valor1)/180);
                    TextField_Principal.setText(sin+"");
                    
                    //SERIALIZAR OPERACION
                    try{
                            f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
                    }catch(Exception e){
                             JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
                    }                    
                    
                    break;
                case "cos":
                    valor1=Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" cos("+valor1+")");
                    cos=Math.cos(Math.PI*(valor1)/180);
                    TextField_Principal.setText(cos+"");
                    //SERIALIZAR OPERACION
                   try{
                           f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
                   }catch(Exception e){
                            JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
                   }                   

                    break;
                case "tan":           
                    valor1=Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" tan("+valor1+")");
                    tan=Math.tan(Math.PI*(valor1)/180);
                    TextField_Principal.setText(tan+"");
                    //SERIALIZAR OPERACION
                    try{
                            f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
                    }catch(Exception e){
                             JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
                    }                    
                    break;
                    
                    
            }
        }
    }
    
    
    
    
    private void Button_CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CosActionPerformed
       funciones="cos";
       Trigonometria();
    }//GEN-LAST:event_Button_CosActionPerformed

    private void Button_SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SinActionPerformed
        funciones="sin";
        Trigonometria();
    }//GEN-LAST:event_Button_SinActionPerformed

    private void Button_TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TanActionPerformed
        funciones="tan";
        Trigonometria();
    }//GEN-LAST:event_Button_TanActionPerformed
//Botón que devuelve el valor de Pi
    private void Button_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PIActionPerformed
      TextField_Previo.setText("PI ");
      TextField_Principal.setText(Math.PI+" ");
    }//GEN-LAST:event_Button_PIActionPerformed

///Botón que eleva un numero a x Potencia
    private void Button_ExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExponenteActionPerformed
       inicio=true;
       valor1=Double.parseDouble(TextField_Principal.getText());
       TextField_Previo.setText(valor1+"^");
       tipoOperaciones="potencia";
       operacion1=false;
       igual=true;
       
            //SERIALIZAR OPERACION
            try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
            }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
            }      
       
    }//GEN-LAST:event_Button_ExponenteActionPerformed

///Botón que devuelve el factorial de un número
    private void Button_FactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FactorialActionPerformed
       a=1;
       valor1= Double.parseDouble(TextField_Principal.getText());
       TextField_Previo.setText("fact ("+valor1+")");
       for(b=1; b<=valor1;b++){
           a=a*b;
       }
       TextField_Principal.setText(a+"");
       
            //SERIALIZAR OPERACION
            try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
            }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
            }       
       
    }//GEN-LAST:event_Button_FactorialActionPerformed
//Botón que devuelve el valor de e
    private void Button_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EActionPerformed
        TextField_Previo.setText("E ");
        TextField_Principal.setText(Math.E+"");

    }//GEN-LAST:event_Button_EActionPerformed

///Botón que eleva 10 a la x potencia
    private void Button_10levarXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_10levarXActionPerformed
        valor1=Double.parseDouble(TextField_Principal.getText());
        TextField_Previo.setText("powten)"+valor1+")");
        TextField_Principal.setText(Math.pow(10,valor1)+" ");
            //SERIALIZAR OPERACION
            try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
            }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
            }        
    }//GEN-LAST:event_Button_10levarXActionPerformed
//Botón de la exponenciación neperiana
    private void Button_EXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EXPActionPerformed
       valor1=Double.parseDouble(TextField_Principal.getText());
       TextField_Principal.setText(Math.exp(valor1)+" ");
            //SERIALIZAR OPERACION
            try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
            }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
            }       
    }//GEN-LAST:event_Button_EXPActionPerformed
//Botón del logaritmo neperiano
    private void Button_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_logActionPerformed
       valor1=Double.parseDouble(TextField_Principal.getText());
       TextField_Previo.setText("log("+valor1+")");
       TextField_Principal.setText(Math.log(valor1)+" ");
            //SERIALIZAR OPERACION
            try{
                    f.agregarOperaciones(TextField_Previo.getText(),Double.parseDouble(TextField_Principal.getText()));
            }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error..." + e.getMessage());
            }       
    }//GEN-LAST:event_Button_logActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        // TODO add your handling code here:
         try {
           
            f.Leer();
             int i=0;
            
           for(Operacion ops: f.Leer()){
               i+=1;
               holaxd.append(ops.getOperacionfinal()+"="+ops.getResultadofinal()+"\n");

             
           }

            
        } catch (IOException ex) {
            Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_10levarX;
    private javax.swing.JButton Button_C;
    private javax.swing.JButton Button_CE;
    private javax.swing.JButton Button_Cos;
    private javax.swing.JButton Button_Decimal;
    private javax.swing.JButton Button_Division;
    private javax.swing.JButton Button_E;
    private javax.swing.JButton Button_EXP;
    private javax.swing.JButton Button_Exponente;
    private javax.swing.JButton Button_Factorial;
    private javax.swing.JButton Button_Multiplicacion;
    private javax.swing.JButton Button_N0;
    private javax.swing.JButton Button_N1;
    private javax.swing.JButton Button_N2;
    private javax.swing.JButton Button_N3;
    private javax.swing.JButton Button_N4;
    private javax.swing.JButton Button_N5;
    private javax.swing.JButton Button_N6;
    private javax.swing.JButton Button_N7;
    private javax.swing.JButton Button_N8;
    private javax.swing.JButton Button_N9;
    private javax.swing.JButton Button_PI;
    private javax.swing.JButton Button_Porcentaje;
    private javax.swing.JButton Button_RaizCuadrada;
    private javax.swing.JButton Button_Resta;
    private javax.swing.JButton Button_Retroseso;
    private javax.swing.JButton Button_Signo;
    private javax.swing.JButton Button_Sin;
    private javax.swing.JButton Button_Suma;
    private javax.swing.JButton Button_Tan;
    private javax.swing.JButton Button_gual;
    private javax.swing.JButton Button_log;
    private javax.swing.JButton Historial;
    private javax.swing.JRadioButton RadioButton_Sexages;
    private javax.swing.JTextField TextField_Previo;
    private javax.swing.JTextField TextField_Principal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea holaxd;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
