/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subneteo;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import static com.sun.xml.internal.fastinfoset.util.ValueArray.MAXIMUM_CAPACITY;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bailarina77
 */
public class VentanaSubne extends javax.swing.JFrame {
    ///CREAMOS LAS VARIABLES
    String IP;
    String []IPS;
    int digito, PO,SO,TO,CO,n,ROB;
    String binario1,binario2,binario3,binario4;

   
    
   public static String binarear(int n, int l ) throws Exception {
       double pow =  Math.pow(2, l);
       StringBuilder binary = new StringBuilder();
        if ( pow < n ) {
            throw new Exception("Que numero mas grande, ingresa algo bien xd ");
        }
       int shift = l- 1;
       for (; shift >= 0 ; shift--) {
           int bit = (n >> shift) & 1;
           if (bit == 1) {
               binary.append("1");
           } else {
               binary.append("0");
           }
       }
       return binary.toString();
   }


    /**
     * Creates new form VentanaSubne
     */
    public VentanaSubne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DIP = new javax.swing.JTextField();
        NR = new javax.swing.JTextField();
        ACEP = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOctetos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mascarita = new javax.swing.JLabel();
        clase = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mascro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUBNETEO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero de Redes");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de Direccion IP:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        DIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIPActionPerformed(evt);
            }
        });
        jPanel3.add(DIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 190, -1));

        NR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NRActionPerformed(evt);
            }
        });
        jPanel3.add(NR, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 140, 20));

        ACEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acep_press.png"))); // NOI18N
        ACEP.setBorder(null);
        ACEP.setBorderPainted(false);
        ACEP.setContentAreaFilled(false);
        ACEP.setFocusPainted(false);
        ACEP.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acep_press.png"))); // NOI18N
        ACEP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acep_roll.png"))); // NOI18N
        ACEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPActionPerformed(evt);
            }
        });
        jPanel3.add(ACEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 20));

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_norm.png"))); // NOI18N
        borrar.setBorder(null);
        borrar.setBorderPainted(false);
        borrar.setContentAreaFilled(false);
        borrar.setFocusPainted(false);
        borrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_press.png"))); // NOI18N
        borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar_roll.png"))); // NOI18N
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel3.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 20));

        tablaOctetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Primer Octeto", "Segundo Octeto", "Tercer Octeto", "Cuarto Octeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaOctetos);
        if (tablaOctetos.getColumnModel().getColumnCount() > 0) {
            tablaOctetos.getColumnModel().getColumn(0).setResizable(false);
            tablaOctetos.getColumnModel().getColumn(1).setResizable(false);
            tablaOctetos.getColumnModel().getColumn(2).setResizable(false);
            tablaOctetos.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 50));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Clase de Red:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mascara Robada:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        mascarita.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        mascarita.setForeground(new java.awt.Color(255, 0, 102));
        jPanel3.add(mascarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        clase.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        clase.setForeground(new java.awt.Color(255, 51, 102));
        jPanel3.add(clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mascara Actual:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        mascro.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        mascro.setForeground(new java.awt.Color(255, 51, 102));
        jPanel3.add(mascro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -80, 840, 830));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DIPActionPerformed

    private void ACEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPActionPerformed
        // TODO add your handling code here:

        IP=DIP.getText();
        //EXPRESION REGULAR PARA SABER SI ES UNA IP
        String pattern = "((?:(?:25[0-5]|2[0-4]\\d|((1\\d{2})|([1-9]?\\d)))\\.){3}(?:25[0-5]|2[0-4]\\d|((1\\d{2})|([1-9]?\\d))))";
        int exp=0;
        int P;
        Icon m= new ImageIcon(getClass().getResource("../Imagenes/error.png"));
        if(IP.matches(pattern)){
            try {
                String[] arrayIP = IP.split("\\.");
                
                //PRIMER OCTECTO
                binario1=binarear(Integer.parseInt(arrayIP[0]),8);
                                
                //PARA EL SEGUNDO OCTECTO
                binario2=binarear(Integer.parseInt(arrayIP[1]),8);
                
                //PARA EL TERCER OCTECTO
                binario3=binarear(Integer.parseInt(arrayIP[2]),8);
                
                //PARA EL CUARTO OCTECTO
                binario4=binarear(Integer.parseInt(arrayIP[3]),8);
                
                //AQUI MANDAMOS LA CLASE QUE ES LA RED
                        if(Integer.parseInt(arrayIP[0])<127){
                            clase.setText("A");
                        }
                        if(Integer.parseInt(arrayIP[0])>127&&Integer.parseInt(arrayIP[0])<191){
                            clase.setText("B");
                        }
                        if(Integer.parseInt(arrayIP[0])>191 && Integer.parseInt(arrayIP[0])<223){
                            clase.setText("C");
                        }
                        
                //AQUI MANDAMOS LA MASCARA QUE ES LA RED
                        if("A".equals(clase.getText())){
                            mascarita.setText("255.0.0.0");
                        }
                        if("B".equals(clase.getText())){
                            mascarita.setText("255.255.0.0");
                        }
                        if("C".equals(clase.getText())){
                            mascarita.setText("255.255.255.0");
                        }     
                        

                
                ///NUESTRA TABLA
                
                String nombreColumnas[]={"Primer Octeto","Segundo Octeto","Tercer Octeto","Cuarto Octeto"};
                String data[][]=new String[1][4];
                
                data[0][0]=binario1;
                data[0][1]=binario2;
                data[0][2]=binario3;
                data[0][3]=binario4;
                
                tablaOctetos.setModel(new DefaultTableModel(data,nombreColumnas));
                
                
                ///MASCARAS DE SUBRED
                int redes = Integer.parseInt(NR.getText());

                int n = redes - 1;
                  n |= n >>> 1;
                  n |= n >>> 2;
                  n |= n >>> 4;
                  n |= n >>> 8;
                  n |= n >>> 16;
                int num = (n < 0) ? 1 : (n >= MAXIMUM_CAPACITY) ? MAXIMUM_CAPACITY : n + 1;

                ROB=(int) (Math.log10(num)/Math.log10(2));
                
                System.out.println("ROBAREMOS "+ROB);
                
            
            } catch (Exception ex) {
                Logger.getLogger(VentanaSubne.class.getName()).log(Level.SEVERE, null, ex);
            }
                        
        }else{
            JOptionPane.showMessageDialog(null,"Error, ingresa algo bien -_-","ERROR 404xD",JOptionPane.INFORMATION_MESSAGE,m);}
        
    }//GEN-LAST:event_ACEPActionPerformed



    
    
    
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        DIP.setText("");
        NR.setText("");
        String nombreColumnas[]={"Primer Octeto","Segundo Octeto","Tercer Octeto","Cuarto Octeto"};          
        Double data[][]=new Double[1][4];
          data[0][0]=0.0;
          data[0][1]=0.0;
          data[0][2]=0.0;
          data[0][3]=0.0;
      tablaOctetos.setModel(new DefaultTableModel(data,nombreColumnas)); 
      mascarita.setText("");
      clase.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void NRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NRActionPerformed

    /**
     * @param args thes command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSubne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSubne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSubne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSubne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSubne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEP;
    private javax.swing.JTextField DIP;
    private javax.swing.JTextField NR;
    private javax.swing.JButton borrar;
    private javax.swing.JLabel clase;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mascarita;
    private javax.swing.JLabel mascro;
    private javax.swing.JTable tablaOctetos;
    // End of variables declaration//GEN-END:variables
}
